const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    // _id is auto-generated by MongoDB
    username: { type: String, required: true, unique: true, trim: true }, // primary key idea
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    password: { type: String, required: true } // encrypted (bcrypt hash) will be stored
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" }
  }
);

module.exports = mongoose.model("User", userSchema);

